require('plugins.compe')
require('plugins.autopairs')
require('plugins.treesitter')
require('plugins.colorizer')
require('plugins.indent_blankline')
require('plugins.todo_comments')
require('plugins.nordevil_lualine')
require('plugins.mason').setup()
